name: iOS CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: 🔎 Check Default Xcode Version 🔎
      run: |
        xcodebuild -version
        xcode-select -p
        ls /Applications | grep Xcode
    
    - name: Get Path
      run: pwd
    
    - name: LS
      run: ls -al
      
    - name: Create Secrets.xcconfig
      run: echo "API_KEY=${{ secrets.API_KEY }}\nSUPABASE_URL=${{ secrets.SUPABASE_URL }}" > "Tekken8 Frame Data/TK8/Secrets.xcconfig"

    - name: Install Dependencies (SPM 의존성)
      run: xcodebuild -resolvePackageDependencies -project "Tekken8 Frame Data/TK8.xcodeproj"

    - name: 🛠️ Build Project 🛠️
      run: xcodebuild clean build -project "Tekken8 Frame Data/TK8.xcodeproj" -scheme "Tekken8 Frame Data" -destination "platform=iOS Simulator,name=iPhone 16,OS=latest"
